layout_spectrum: 0.9709760302145698
typography_spectrum: 0.5180123833463629
color:
  brandStrength: 0.9037474204477218
  lightness: 0.21515445745503992
  saturation: 0.468288121906727
  rhythmicContrast: 0.9911168382762203
  brandColors:
    - '#FF3D5A'
    - '#FF0000'
    - '#FF0055'
    - '#FF3333'
    - '#FF2449'
github: true
name: Electronic Press Kit
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
  - name: About
    id: fce72724-2348-43a3-be63-e95fadc73acb
    type: content
title: ENIX INRI
content: []
description: ' Composer, Vocalist , Sound Designer'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
