layout_spectrum: 0.41198160557279195
typography_spectrum: 0.515810460366198
color:
  brandStrength: 0.09401978433537896
  lightness: 0.03759567533813343
  saturation: 0.7354024588731625
  rhythmicContrast: 0.06199369186913539
  brandColors:
    - '#000000'
    - '#FFD119'
    - '#FF19FF'
    - '#00CCFF'
    - '#4719FF'
github: true
name: Electronic Press Kit
navigation:
  - name: Spotify
    url: >-
      https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjNz8ey_dfYAhWtS98KHTwxDAkQFggpMAA&url=https%3A%2F%2Fopen.spotify.com%2Fartist%2F7nSc6SnLWDwDoAjMueAqvh&usg=AOvVaw1CC4VFI1ZnUh5yWms0NoNd
    type: external
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
  - name: About
    id: fce72724-2348-43a3-be63-e95fadc73acb
    type: content
  - name: Music & Sound Contributor
    url: 'https://cosmictriggerplay.com/the-play/crew-2017/'
    type: external
title: ENIX INRI
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d8b5ca7-86e7-42b3-aabf-d2ff69676290.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d8b5ca7-86e7-42b3-aabf-d2ff69676290.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ' Composer, Vocalist , Sound Designer'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
