layout_spectrum: 0.07134395067764465
typography_spectrum: 0.17309909194348252
color:
  brandStrength: 0.49056198151496305
  lightness: 0.29400465167597817
  saturation: 0.5798421193756126
  rhythmicContrast: 0.8693296512196044
  brandColors:
    - '#141414'
    - '#BC00DA'
    - '#7600DA'
    - '#4A07A3'
    - '#360C6D'
github: true
name: Electronic Press Kit
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
  - name: About
    id: fce72724-2348-43a3-be63-e95fadc73acb
    type: content
title: ENIX INRI
content: []
description: ' Composer, Vocalist , Sound Designer'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
