typography_spectrum: 0.5826073560031075
color:
  brandStrength: 0.13058319468493804
  lightness: 0.9738324557959406
  saturation: 0.13883250369109434
  rhythmicContrast: 0.13867791506139063
  brandColors:
    - '#07060B'
    - '#878787'
    - '#414141'
    - '#A6B7F1'
    - '#E346DB'
github: true
layout_spectrum: 0.5544044560780472
name: Electronic Press Kit
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
title: ENIX INRI
content: []
description: ' Composer, Vocalist , Sound Designer,'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
