typography_spectrum: 0.6388387202715852
color:
  brandStrength: 0.5476365650995718
  lightness: 0.4424051542167948
  saturation: 0.9609513872025516
  rhythmicContrast: 0.6449955866110539
  brandColors:
    - '#4E0229'
    - '#963B99'
    - '#B079D9'
    - '#FEE9FE'
    - '#F7A9FF'
github: true
layout_spectrum: 0.3471358930752936
name: THIRD EYE RESEARCH INSTITUTE
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
title: ENIX INRI
content: []
description: ' gnarly nexus of visionary cultures and disruptive technologies'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
