layout_spectrum: 0.13942460584251376
typography_spectrum: 0.3276068729314363
color:
  brandStrength: 0.16681146536953748
  lightness: 0.921856357020575
  saturation: 0.6066809380256414
  rhythmicContrast: 0.3359956859031895
  brandColors:
    - '#050016'
    - '#934195'
    - '#FFDB87'
    - '#98FEFD'
    - '#16E2FE'
github: true
name: Electronic Press Kit
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
  - name: About
    id: fce72724-2348-43a3-be63-e95fadc73acb
    type: content
title: ENIX INRI
content: []
description: ' Composer, Vocalist , Sound Designer'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
