layout_spectrum: 0.7590363001045172
typography_spectrum: 0.4415662785845412
color:
  brandStrength: 0.9571565329770345
  lightness: 0.2844268920284576
  saturation: 0.07525899339319751
  rhythmicContrast: 0.8742214742585057
  brandColors:
    - '#FFFEFF'
    - '#0E0405'
    - '#FE4481'
    - '#8B806F'
    - '#6FBBAE'
github: true
name: THIRD EYE RESEARCH INSTITUTE
navigation:
  - name: Bandcamp
    url: 'https://enix-inri.bandcamp.com/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/enix-inri'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UClTDLHfiEPmNns3G1BBDueQ'
    type: external
  - name: About
    id: fce72724-2348-43a3-be63-e95fadc73acb
    type: content
title: ENIX INRI
content: []
description: ' gnarly nexus of visionary cultures and disruptive technologies'
purpose:
  - type: contact
    url: 'tel:2675152479'
    label: 'Call '
  - type: contact
    url: 'mailto:enix.inri@gmail.com'
    label: Email
